### PR TITLE
Created keyboard Model

### PR DESCRIPTION
**Pull request by DewinP**
### Assignee Tasks

* [ ] added unit tests (or none needed)
* [ ] written relevant docs (or none needed)
* [ ] referenced any relevant issues (or none exist)

### Guidelines

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.

---

_Your PR Notes Here_

### CODE REVIEW

**Review by LindaEng — COMMENTED** [review]
Look's fine and dandy

**Comment by sergethi** [comment]
Great

**Review by sergethi — APPROVED** [review]

**Review by LindaEng — COMMENTED** [review]
everything checked and approved

**Review by LindaEng — COMMENTED** [review]
approved

**Pull request merged**
